OAS-4983 | update docs for getting started guide
arangodb-managed/terraform-provider-oasis pull request #55
Opened 2022-06-02 09:48 UTC by adoi

2022-06-03 13:00 UTC, ansoboleva requested changes

2022-06-03 15:53 UTC, adoi commented on docs/guides/getting-started.md
> +ArangoDB Oasis, the ArangoDB Cloud, provides ArangoDB databases as a Service (DBaaS). It enables you to use the entire functionality of an ArangoDB cluster deployment without the need to run or manag
As discussed, this is something we will decide for in the future, at the moment it is based on [ArangoDB Oasis Docs](https://www.arangodb.com/docs/stable/oasis/)

2022-06-03 16:48 UTC, ansoboleva commented on docs/guides/getting-started.md
> +Log in to the Oasis dashboard and open the [API Keys](https://cloud.arangodb.com/dashboard/user/api-keys) tab of your user account. Click the New API key button to generate a new key, which can be us
should be bold as it is a UI element

2022-06-03 16:48 UTC, ansoboleva commented on docs/guides/setup.md
> +When using the provider, you need to set up api_key_id and api_key_secret. Both parameters can be generated in the Oasis Dashboard. Once you are logged in, navigate to the [API Keys](https://cloud.ar
The button name should be bold as it is a UI element

2022-06-03 16:52 UTC, ansoboleva approved these changes
please address two comments about the formatting, otherwise LGTM

2022-06-04 11:22 UTC, ewoutp requested changes

2022-06-04 11:22 UTC, ewoutp commented on docs/guides/getting-started.md
> +ArangoDB Oasis, the ArangoDB Cloud, provides ArangoDB databases as a Service (DBaaS). It enables you to use the entire functionality of an ArangoDB cluster deployment without the need to run or manag
Please remove the word cluster

2022-06-04 11:22 UTC, ewoutp commented on docs/guides/getting-started.md
> +Terraform Provider Oasis is a plugin for Terraform that allows for the full lifecycle management of ArangoDB Cloud resources.
We need naming. The line before it is called ArangoDB Oasis and here ArangoDB cloud

2022-06-04 11:22 UTC, ewoutp commented on templates/guides/getting-started.md.tmpl
> +Terraform Provider Oasis is a plugin for Terraform that allows for the full lifecycle management of ArangoDB Cloud resources.
Same as before

2022-06-10 08:56 UTC, merged